import os
import json
import sqlite3
import secrets
import logging
import re
from functools import wraps

import bcrypt
from flask import (
    Flask, render_template, request, redirect,
    url_for, make_response, flash, session, abort
)
from flask_wtf import CSRFProtect
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from werkzeug.utils import secure_filename

from extractor import (
    extract_group, extract_schedule,
    group_year, is_older_than,
)

# ==================== CONFIG ====================
ADMIN_USER = "mohammedbekhit"

# Paste the bcrypt hash generated by hash_password.py here
ADMIN_PASSWORD_HASH = b"$2b$12$115xCMjbEvXL2SaYyS3aie4yrsCD7gKOcxXMYndNwiLMMV.tZkjgS"

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
UPLOAD_DIR = os.path.join(BASE_DIR, "uploads")
DB_PATH = os.path.join(BASE_DIR, "schedules.db")
os.makedirs(UPLOAD_DIR, exist_ok=True)

# ==================== APP ====================
app = Flask(__name__)
app.secret_key = os.environ.get("SECRET_KEY") or secrets.token_hex(32)
app.config.update(
    SESSION_COOKIE_HTTPONLY=True,
    SESSION_COOKIE_SAMESITE="Lax",
    SESSION_COOKIE_SECURE=False,     # True in production w/ HTTPS
    WTF_CSRF_TIME_LIMIT=None,
)

csrf = CSRFProtect(app)

limiter = Limiter(
    key_func=get_remote_address,
    app=app,
    default_limits=["600 per hour"],
    storage_uri="memory://",
)

logging.basicConfig(level=logging.INFO)
log = logging.getLogger("app")


# ==================== SECURITY HEADERS ====================
@app.after_request
def set_security_headers(resp):
    resp.headers["X-Content-Type-Options"] = "nosniff"
    resp.headers["X-Frame-Options"] = "DENY"
    resp.headers["Referrer-Policy"] = "strict-origin-when-cross-origin"
    resp.headers["Permissions-Policy"] = "geolocation=(), microphone=(), camera=()"
    resp.headers["Content-Security-Policy"] = (
        "default-src 'self'; "
        "style-src 'self' 'unsafe-inline'; "
        "script-src 'self' 'unsafe-inline'; "
        "img-src 'self' data:; "
        "font-src 'self' data:; "
        "frame-ancestors 'none'; "
        "base-uri 'self'; "
        "form-action 'self'"
    )
    return resp


# ==================== DATABASE ====================
def init_db():
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS schedules (
                group_name  TEXT PRIMARY KEY,
                schedule    TEXT NOT NULL,
                pdf_name    TEXT,
                uploaded_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS settings (
                key   TEXT PRIMARY KEY,
                value TEXT NOT NULL
            )
        """)
        # Default settings if missing
        defaults = {
            "current_year": "26",     # reference year (2-digit)
            "max_age_years": "5",     # delete groups older than this many years
        }
        for k, v in defaults.items():
            conn.execute(
                "INSERT OR IGNORE INTO settings (key, value) VALUES (?, ?)",
                (k, v)
            )
        conn.commit()


# -------- schedules --------
def save_schedule(group_name: str, schedule: dict, pdf_name: str = ""):
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute(
            "INSERT OR REPLACE INTO schedules (group_name, schedule, pdf_name) "
            "VALUES (?, ?, ?)",
            (group_name, json.dumps(schedule, ensure_ascii=False), pdf_name)
        )
        conn.commit()


def get_schedule(group_name: str):
    with sqlite3.connect(DB_PATH) as conn:
        row = conn.execute(
            "SELECT schedule FROM schedules WHERE group_name = ?",
            (group_name,)
        ).fetchone()
    return json.loads(row[0]) if row else None


def list_groups():
    with sqlite3.connect(DB_PATH) as conn:
        rows = conn.execute(
            "SELECT group_name FROM schedules ORDER BY group_name"
        ).fetchall()
    return [r[0] for r in rows]


def delete_group(group_name: str):
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute("DELETE FROM schedules WHERE group_name = ?", (group_name,))
        conn.commit()


# -------- settings --------
def get_setting(key: str, default: str = "") -> str:
    with sqlite3.connect(DB_PATH) as conn:
        row = conn.execute(
            "SELECT value FROM settings WHERE key = ?", (key,)
        ).fetchone()
    return row[0] if row else default


def set_setting(key: str, value: str):
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute(
            "INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)",
            (key, str(value))
        )
        conn.commit()


def get_all_settings() -> dict:
    with sqlite3.connect(DB_PATH) as conn:
        rows = conn.execute("SELECT key, value FROM settings").fetchall()
    return {k: v for k, v in rows}


init_db()


# ==================== AUTH ====================
def admin_required(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        if not session.get("is_admin"):
            return redirect(url_for("admin_login"))
        return f(*args, **kwargs)
    return wrapper


# ==================== INPUT VALIDATION ====================
GROUP_RE = re.compile(r'^[A-Za-zА-Яа-я0-9_\-]{1,40}$')

def is_valid_group(g: str) -> bool:
    return bool(g and GROUP_RE.match(g))


# ==================== PUBLIC ROUTES ====================
@app.route("/")
def index():
    groups = list_groups()
    saved_group = request.cookies.get("group")
    if saved_group and is_valid_group(saved_group) and saved_group in groups:
        return redirect(url_for("schedule", group=saved_group))
    return render_template("index.html", groups=groups)


@app.route("/schedule")
def schedule():
    group = request.args.get("group", "").strip()
    remember = request.args.get("remember") == "1"

    if not is_valid_group(group):
        flash("Invalid group name.", "error")
        return redirect(url_for("index"))

    data = get_schedule(group)
    if not data:
        flash("Schedule not found.", "error")
        return redirect(url_for("index"))

    days = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"]
    all_times = set()
    for d in days:
        for t in data.get(d, {}).get("time_slots", {}).keys():
            all_times.add(t)
    all_times = sorted(all_times, key=lambda x: x.split('-')[0])

    resp = make_response(render_template(
        "schedule.html",
        group=group, data=data, days=days, times=all_times
    ))

    if remember:
        resp.set_cookie("group", group, max_age=60*60*24*365,
                        httponly=True, samesite="Lax")
    else:
        resp.delete_cookie("group")
    return resp


@app.route("/forget")
def forget():
    resp = make_response(redirect(url_for("index")))
    resp.delete_cookie("group")
    return resp


# ==================== ADMIN LOGIN ====================
@app.route(f"/{ADMIN_USER}", methods=["GET", "POST"])
@limiter.limit("5 per minute", methods=["POST"])
def admin_login():
    if request.method == "POST":
        password = request.form.get("password", "")
        try:
            ok = bcrypt.checkpw(password.encode("utf-8"), ADMIN_PASSWORD_HASH)
        except Exception as e:
            log.warning(f"bcrypt error: {e}")
            ok = False

        if ok:
            session.clear()
            session["is_admin"] = True
            log.info("Admin login from %s", get_remote_address())
            return redirect(url_for("admin_panel"))

        log.warning("Failed admin login from %s", get_remote_address())
        flash("Wrong password.", "error")

    return render_template("admin_login.html", admin_user=ADMIN_USER)


# ==================== ADMIN PANEL ====================
ALLOWED_EXT = {".pdf"}
MAX_PDF_BYTES = 20 * 1024 * 1024


@app.route("/admin/panel", methods=["GET", "POST"])
@admin_required
def admin_panel():
    if request.method == "POST":
        pdf = request.files.get("pdf")
        if not pdf or not pdf.filename:
            flash("No file selected.", "error")
            return redirect(url_for("admin_panel"))

        ext = os.path.splitext(pdf.filename)[1].lower()
        if ext not in ALLOWED_EXT:
            flash("Only .pdf files are allowed.", "error")
            return redirect(url_for("admin_panel"))

        pdf.stream.seek(0, os.SEEK_END)
        size = pdf.stream.tell()
        pdf.stream.seek(0)
        if size > MAX_PDF_BYTES:
            flash("File too large (max 20 MB).", "error")
            return redirect(url_for("admin_panel"))

        safe_name = secure_filename(pdf.filename) or "upload.pdf"
        safe_name = f"{secrets.token_hex(4)}_{safe_name}"
        save_path = os.path.join(UPLOAD_DIR, safe_name)
        pdf.save(save_path)

        try:
            group = extract_group(save_path)
            if not is_valid_group(group):
                raise ValueError(f"Invalid group name: {group}")
            schedule = extract_schedule(save_path)
            save_schedule(group, schedule, safe_name)
            flash(f"Uploaded & parsed group: {group}", "success")
            log.info("Uploaded schedule for %s", group)
        except Exception as e:
            log.exception("Parse failed")
            flash(f"Failed to parse PDF: {e}", "error")

        return redirect(url_for("admin_panel"))

    settings = get_all_settings()
    groups = list_groups()
    return render_template(
        "admin.html",
        groups=groups,
        settings=settings,
        admin_user=ADMIN_USER,
    )


@app.route("/admin/delete/<group>", methods=["POST"])
@admin_required
def admin_delete(group):
    if not is_valid_group(group):
        abort(400)
    delete_group(group)
    flash(f"Deleted group: {group}", "success")
    return redirect(url_for("admin_panel"))


# ==================== SETTINGS API ====================
@app.route("/admin/settings", methods=["POST"])
@admin_required
def admin_save_settings():
    """
    Save current_year and max_age_years from the admin form.
    Both are validated: current_year ∈ [0..99], max_age_years ∈ [0..30].
    """
    cur_raw = request.form.get("current_year", "").strip()
    age_raw = request.form.get("max_age_years", "").strip()

    if not cur_raw.isdigit() or not (0 <= int(cur_raw) <= 99):
        flash("Current year must be a 2-digit number (00–99).", "error")
        return redirect(url_for("admin_panel"))

    if not age_raw.isdigit() or not (0 <= int(age_raw) <= 30):
        flash("Max age must be an integer between 0 and 30.", "error")
        return redirect(url_for("admin_panel"))

    set_setting("current_year", cur_raw)
    set_setting("max_age_years", age_raw)
    flash(f"Settings saved: current_year={cur_raw}, max_age_years={age_raw}", "success")
    return redirect(url_for("admin_panel"))


# ==================== CLEANUP BY AGE ====================
@app.route("/admin/cleanup-by-age", methods=["POST"])
@admin_required
def admin_cleanup_by_age():
    """
    Delete every group older than `max_age_years` relative to `current_year`.
    Uses the settings saved in the DB.
    """
    try:
        current_year = int(get_setting("current_year", "26"))
        max_age = int(get_setting("max_age_years", "5"))
    except ValueError:
        flash("Invalid stored settings.", "error")
        return redirect(url_for("admin_panel"))

    removed = []
    for g in list_groups():
        if is_older_than(g, current_year, max_age):
            delete_group(g)
            removed.append(g)

    if removed:
        flash(
            f"Removed {len(removed)} group(s) older than {max_age} years "
            f"(relative to {current_year}): {', '.join(removed)}",
            "success"
        )
    else:
        flash(
            f"Nothing to clean — no groups older than {max_age} years "
            f"relative to {current_year}.",
            "success"
        )
    return redirect(url_for("admin_panel"))


# ==================== CLEANUP BY SPECIFIC YEAR ====================
@app.route("/admin/cleanup-by-year", methods=["POST"])
@admin_required
def admin_cleanup_by_year():
    """
    Delete every group that matches a specific 2-digit year (e.g. 20).
    """
    target_raw = request.form.get("target_year", "").strip()
    if not target_raw.isdigit() or not (0 <= int(target_raw) <= 99):
        flash("Target year must be a 2-digit number (00–99).", "error")
        return redirect(url_for("admin_panel"))

    target = int(target_raw)
    removed = []
    for g in list_groups():
        if group_year(g) == target:
            delete_group(g)
            removed.append(g)

    if removed:
        flash(f"Removed {len(removed)} group(s) with year {target:02d}: "
              f"{', '.join(removed)}", "success")
    else:
        flash(f"No groups found with year {target:02d}.", "success")
    return redirect(url_for("admin_panel"))


@app.route("/admin/logout")
def admin_logout():
    session.clear()
    return redirect(url_for("index"))


# ==================== ERROR HANDLERS ====================
@app.errorhandler(429)
def ratelimit(e):
    return "Too many requests. Please try again later.", 429


if __name__ == "__main__":
    app.run(debug=False, host="0.0.0.0", port=5000)